const enum SortBy {
	DEFAULT = 'DEFAULT',
	NAME = 'NAME',
	TIME = 'TIME',
	DISTANCE = 'DISTANCE',
	ROUTE_DISTANCE = 'ROUTE_DISTANCE',
	OBJECTS_COUNT = 'OBJECTS_COUNT',
	RATING_AVG = 'RATING_AVG',
	RATING_COUNT = 'RATING_COUNT'
}

export default SortBy;
